name: campus_calibrator
description: "Campulse project demo caliberator."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  geolocator: ^11.0.0
  sensors_plus: ^6.0.1
  flutter_compass: ^0.8.0
  path_provider: ^2.1.4
  share_plus: ^10.0.2
  connectivity_plus: ^6.0.5
  network_info_plus: ^6.0.1
  package_info_plus: ^8.0.0
  wakelock_plus: ^1.2.8
  shared_preferences: ^2.2.3
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/splash/logo.png



flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/splash/logo.png
  adaptive_icon_background: "#053668"
  adaptive_icon_foreground: assets/splash/logo.png
  min_sdk_android: 21

flutter_native_splash:
  color: "#053668"
  image: assets/splash/logo.png
  android_12:
    color: "#053668"
    image: assets/splash/logo.png